---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-emgr-prereqs
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/hook: Sync
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ARGOCD_NAMESPACE
              value: openshift-gitops
            - name: IBM_ENTITLEMENT_SECRET
              value: ibm-entitlement-key
            - name: TARGET_NAMESPACE
              value: "{{.Values.spec.eventManager.namespace}}"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x

              result=0

              # https://www.ibm.com/docs/en/noi/1.6.4?topic=preparing-your-cluster
              oc get ServiceAccount noi-service-account --namespace "${TARGET_NAMESPACE}" -o yaml 2> /dev/null \
              && echo "INFO: NOI service account exists." \
              || {
                  echo "INFO: Create the NOI service account with the entitlement key pull secret."
                  oc create serviceaccount noi-service-account -n "${TARGET_NAMESPACE}" \
                  && oc adm policy add-scc-to-user privileged system:serviceaccount:${TARGET_NAMESPACE}:noi-service-account \
                  && oc get sa noi-service-account -n "${TARGET_NAMESPACE}" \
                  || result=1

                  if [ ! ${result} -eq 0 ]; then
                    oc delete ServiceAccount noi-service-account --namespace "${TARGET_NAMESPACE}"
                  fi
              }

              if [ ${result} -eq 0 ]; then
                  echo "INFO: Event Manager prereq configuration successful."
              else
                  echo "ERROR: Event Manager prereq configuration failed."
              fi

              exit ${result}

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-noi
  backoffLimit: 1
