apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  zen:
    serviceInstanceName: iaf-zen-cpdservice
    serviceNamespace: ''
  serviceContinuity:
    continuousAnalyticsCorrelation: false
    isBackupDeployment: false
  ldap:
    port: '3389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '3636'
    url: 'ldap://localhost:3389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: {{.Values.spec.storageClass}}
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    iafCartridgeRequirementsName: ''
    netDisco: false
    observers:
      docker: true
      taddm: true
      servicenow: true
      ibmcloud: true
      alm: true
      viptela: true
      contrail: true
      cienablueplanet: true
      kubernetes: true
      bigfixinventory: true
      junipercso: true
      dns: true
      itnm: true
      ansibleawx: true
      hpnfvd: true
      ciscoaci: true
      azure: true
      rancher: true
      newrelic: true
      vmvcenter: true
      rest: true
      appdynamics: true
      jenkins: true
      zabbix: true
      bigcloudfabric: true
      file: true
      googlecloud: true
      dynatrace: true
      aws: true
      openstack: true
      vmwarensx: true
    storageClassElasticTopology: {{.Values.spec.storageClass}}
    storageClassFileObserver: {{.Values.spec.storageClass}}
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
  version: {{.Values.spec.eventManager.version}}
  entitlementSecret: ibm-entitlement-key
  clusterDomain: {{.Values.spec.eventManager.clusterDomain}}
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: {{.Values.spec.storageClass}}
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: {{.Values.spec.storageClass}}
    storageClassKafka: {{.Values.spec.storageClass}}
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: {{.Values.spec.storageClassLargeBlock}}
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: {{.Values.spec.storageClass}}
    storageClassCouchdb: {{.Values.spec.storageClass}}
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: {{.Values.spec.storageClass}}
    storageSizeCassandraData: 50Gi
    storageClassElastic: {{.Values.spec.storageClass}}
    storageClassImpactGUI: {{.Values.spec.storageClass}}
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: {{.Values.spec.storageClassLargeBlock}}
  deploymentType: {{.Values.spec.eventManager.deploymentType}}
