site_name: IBM Cloud Pak for Watson AIOps
site_url: https://ibm.github.io/cp4waiops-gitops/docs/
repo_url: https://github.com/IBM/cp4waiops-gitops
nav:
    - GitOps Install:
      - Introduction: README.md
      - v3.6 Official Support:
        - Online Install: how-to-deploy-cp4waiops-36.md
      - v3.7 Official Support:
        - Online Install: how-to-deploy-cp4waiops-37.md
      - v4.1 Official Support:
        - Online Install: how-to-deploy-cp4waiops-41.md
        
theme:
    name: material
    # logo: images/logo.png
    # favicon: images/logo.png
    palette:
      scheme: default
      primary: black
    font:
      text: IBM Plex Sans
      code: IBM Plex Mono
    language: en
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.sections
use_directory_urls: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/snippets
extra_css:
    - css/extra.css
