---
###################################
# CP4WAIOps - Common Configs
###################################
spec:

  ## AI Manager catalog source image
  ##
  imageCatalog: icr.io/cpopen/ibm-operator-catalog:latest

  ## dockerUsername is the usrname of IBM® Entitled Registry.
  ## It is used to create a docker-registry secret to enable your deployment to pull the AI Manager images 
  ## from the IBM® Entitled Registry.
  ## Default is cp
  dockerUsername: cp

  ## Obtain the entitlement key that is assigned to your IBMid. 
  ## Log in to MyIBM Container Software Library: https://myibm.ibm.com/products-services/containerlibrary
  ## Opens in a new tab with the IBMid and password details 
  ## that are associated with the entitled software.
  ## DO NOT Commit your docker password here, but always specify it in UI or CLI when creating the ArgoCD app.
  ## 
  dockerPassword: password

  ## storageClass is the storage class that you want to use. 
  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-cephfs
  ##
  storageClass: rook-cephfs

  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-ceph-rbd
  storageClassLargeBlock: rook-cephfs

  aiManager:
    ## Enable AI Manager
    ##
    enabled: true

    ## A channel defines a stream of updates for an Operator and is used to roll out updates for subscribers. 
    ## For example, if you want to install AI Manager 3.2, the channel should be v3.2
    ##
    channel: v3.2

    ## size is the size that you require for your AI Manager installation. It can be small or large.
    ## More information: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-watson-aiops/3.2.0?topic=requirements-ai-manager
    size: small

    ## namespace is the project (namespace) that you want to create the AI Manager instance in.
    ## You must create a custom project (namespace) and not use the default, kube-system,
    ## kube-public, openshift-node, openshift-infra, or openshift projects (namespaces). 
    ## This is because AI Manager uses Security Context Constraints (SCC), 
    ## and SCCs cannot be assigned to pods created in one of the default OpenShift projects (namespaces).
    ##
    namespace: cp4waiops
