# -----------------------------------------------------------------------------
# Argo CD parameters
# -----------------------------------------------------------------------------
argocd:

  # The type of the cluster that Argo CD runs on, values includes:
  # - kubernetes
  # - openshift
  cluster: openshift

  # The Argo CD namespace that can be auto-resolved based on cluster type,
  # or you can uncomment below parameter to specificy it explicitly.
  # namespace: argocd

  # Allow apps to be deployed on the same cluster where Argo CD runs.
  allowLocalDeploy: true

# -----------------------------------------------------------------------------
# Storage parameters
# -----------------------------------------------------------------------------
rookceph:

  # Specify whether or not to install Rook Ceph as storage used by CP4WAIOps.
  enabled: false
  
# -----------------------------------------------------------------------------
# CP4WAIOps parameters
# -----------------------------------------------------------------------------
cp4waiops:

  ## dockerUsername is the usrname of IBM® Entitled Registry.
  ## It is used to create a docker-registry secret to enable your deployment to pull the AI Manager images 
  ## from the IBM® Entitled Registry.
  ## Default is cp
  dockerUsername: cp

  ## Obtain the entitlement key that is assigned to your IBMid. 
  ## Log in to MyIBM Container Software Library: https://myibm.ibm.com/products-services/containerlibrary
  ## Opens in a new tab with the IBMid and password details 
  ## that are associated with the entitled software.
  ## DO NOT Commit your docker password here, but always specify it in UI or CLI when creating the ArgoCD app.
  ## 
  dockerPassword: REPLACE_IT

  ## storageClass is the storage class that you want to use. 
  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-cephfs
  ##
  storageClass: rook-cephfs

  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-ceph-rbd
  storageClassLargeBlock: rook-cephfs

  aiManager:
    ## Enable AI Manager
    ##
    enabled: true

    ## AI Manager catalog source image
    ##
    imageCatalog: icr.io/cpopen/ibm-operator-catalog:latest

    ## A channel defines a stream of updates for an Operator and is used to roll out updates for subscribers. 
    ## For example, if you want to install AI Manager 3.2, the channel should be v3.2
    ##
    channel: v3.3

    ## size is the size that you require for your AI Manager installation. It can be small or large.
    ## More information: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-watson-aiops/3.2.0?topic=requirements-ai-manager
    size: small

    ## namespace is the project (namespace) that you want to create the AI Manager instance in.
    ## You must create a custom project (namespace) and not use the default, kube-system,
    ## kube-public, openshift-node, openshift-infra, or openshift projects (namespaces). 
    ## This is because AI Manager uses Security Context Constraints (SCC), 
    ## and SCCs cannot be assigned to pods created in one of the default OpenShift projects (namespaces).
    ##
    namespace: katamari

    ## enable pakModules
    pakModules:
      aiopsFoundation:
        enabled: true
      applicationManager:
        enabled: true
      aiManager:
        enabled: true
      connection:
        enabled: true

  eventManager:
    ## Enable Event Manager
    ##
    enabled: true

    ## Event Manager catalog source image
    ##
    imageCatalog: icr.io/cpopen/ibm-operator-catalog:latest

    # eventManager version
    version: 1.6.4.0

    ## Use the fully qualified domain name (FQDN) to formulate the clusterDomain property, using the following formula:
    ##
    clusterDomain: apps.clustername.*.*.com

    ## A channel defines a stream of updates for an Operator and is used to roll out updates for subscribers. 
    ## For example, if you want to install Evemt Manager 1.5, the channel should be v1.5
    ##
    channel: v1.7

    ## Deployment type (trial or production)
    ## 
    deploymentType: trial

    ## namespace is the project (namespace) that you want to create the Event Manager instance in.
    ## You must create a custom project (namespace) and not use the default, kube-system,
    ## kube-public, openshift-node, openshift-infra, or openshift projects (namespaces). 
    ##
    namespace: noi
