{{- if .Values.spec.aiManager.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  finalizers:
  - kubernetes
{{- end }}