---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-patch
  annotations:
    argocd.argoproj.io/sync-wave: "130"
  namespace: {{.Values.spec.cp4waiops_namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -x

              while : ; do
                ai_ir=$(oc get AIOpsAnalyticsOrchestrator aiops -n {{.Values.spec.cp4waiops_namespace}} -o jsonpath={.kind})
                if [[ $? != 0 ]]; then
                  echo '"AIOpsAnalyticsOrchestrator" has not been created yet.'
                  sleep 10s
                else
                  break
                fi
              done

              cat <<EOF | oc apply -n {{.Values.spec.cp4waiops_namespace}} -f -
                apiVersion: ai.ir.aiops.ibm.com/v1beta1
                kind: AIOpsAnalyticsOrchestrator
                metadata:
                  name: aiops
                spec:
                  pullSecrets:
                  - ibm-entitlement-key
              EOF

              while : ; do
                aiops_topology=$(oc get sa aiops-topology-service-account -n {{.Values.spec.cp4waiops_namespace}} -o jsonpath={.metadata.name})
                if [[ $? != 0 ]]; then
                  echo 'Serviceaccount "aiops-topology-service-account" has not been created yet.'
                  sleep 10s
                else
                  break
                fi
              done

              cat <<EOF | oc apply -n {{.Values.spec.cp4waiops_namespace}} -f -
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: aiops-topology-service-account
                  labels:
                    managedByUser: 'true'
                imagePullSecrets:
                  - name: ibm-entitlement-key
              EOF

              aiops_topology_name=$(kubectl get pod -n {{.Values.spec.cp4waiops_namespace}} | grep aiops-topology-cassandra-auth-secret-generator | awk '{print $1}')
              if [[ "${aiops_topology_name}" != "" ]]; then
                oc delete pod ${aiops_topology_name} -n {{.Values.spec.cp4waiops_namespace}}
              fi

              aiops_ir_name=$(kubectl get pod -n {{.Values.spec.cp4waiops_namespace}} | grep aiops-ir-analytics | awk '{print $1}')
              if [[ "${aiops_ir_name}" != "" ]]; then
                oc delete pod ${aiops_ir_name} -n {{.Values.spec.cp4waiops_namespace}}
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin
  backoffLimit: 4
