apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noi
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "61"
spec:
  channel: {{.Values.spec.eventManager.channel}}
  installPlanApproval: Automatic
  name: noi
  source: ibm-cp-waiops-catalog
  sourceNamespace: openshift-marketplace