apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  channel: {{.Values.spec.aiManager.channel}}
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-cp-waiops-catalog
  sourceNamespace: openshift-marketplace