{{- if .Values.cp4waiops.aiManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aimanager-app
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-aimanager` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: '{{ .Values.cp4waiops.aiManager.namespace }}'
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: config/3.3/aiManager
        repoURL: https://github.com/liyanwei93/cp4waiops-gitops
        targetRevision: release-3.3
        helm:
          valueFiles:
            - values.yaml
          {{- if eq .Values.cp4waiops.aiManager.size "small" }}
            - values.small.yaml
          {{- end }}
          {{- if eq .Values.cp4waiops.aiManager.size "large" }}
            - values.large.yaml
          {{- end }}
          parameters:
            - name: spec.dockerUsername
              value: '{{ .Values.cp4waiops.dockerUsername }}'
            - name: spec.dockerPassword
              value: '{{ .Values.cp4waiops.dockerPassword }}'
            - name: spec.imageCatalog
              value: '{{ .Values.cp4waiops.imageCatalog }}'
            - name: spec.storageClass
              value: '{{ .Values.cp4waiops.storageClass }}'
            - name: spec.storageClassLargeBlock
              value: '{{ .Values.cp4waiops.storageClassLargeBlock }}'
            - name: spec.aiManager.channel
              value: '{{ .Values.cp4waiops.aiManager.channel }}'
            - name: spec.aiManager.namespace
              value: '{{ .Values.cp4waiops.aiManager.namespace }}'
            - name: spec.aiManager.size
              value: '{{ .Values.cp4waiops.aiManager.size }}'
            - name: spec.aiManager.pakModules.aiopsFoundation.enabled
              value: '{{ .Values.cp4waiops.aiManager.pakModules.aiopsFoundation.enabled }}'
            - name: spec.aiManager.pakModules.applicationManager.enabled
              value: '{{ .Values.cp4waiops.aiManager.pakModules.applicationManager.enabled }}'
            - name: spec.aiManager.pakModules.aiManager.enabled
              value: '{{ .Values.cp4waiops.aiManager.pakModules.aiManager.enabled }}'
            - name: spec.aiManager.pakModules.connection.enabled
              value: '{{ .Values.cp4waiops.aiManager.pakModules.connection.enabled }}'
      ignoreDifferences:
        - group: orchestrator.aiops.ibm.com
          jsonPointers:
            - /spec/pakModules
          kind: Installation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
