{{- if .Values.spec.eventManager.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cp4waiops-operator-group
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{.Values.spec.eventManager.namespace}}
{{- end }}